#ifndef __UNKNOWN_ERROR__
#define __UNKNOWN_ERROR__

typedef enum
{
    UNK_ERROR_NONE = 0,                // NO ERROR OCCURRED
    UNK_ERROR_NH_RADIUS_TOO_BIG = 1,   // NEIGHBORHOOD RADIUS EXCEEDS MAXIMUM ALLOWED SIZE FOR THE CORTEX
    UNK_ERROR_FAILED_ALLOC = 2,        // MEMORY ALLOCATION OPERATION FAILED - SYSTEM MAY BE OUT OF MEMORY
    UNK_ERROR_CORTEX_UNALLOC = 3,      // ATTEMPTED TO ACCESS AN UNALLOCATED CORTEX STRUCTURE
    UNK_ERROR_SIZE_WRONG = 4,          // CORTEX DIMENSIONS DO NOT MATCH REQUIRED SPECIFICATIONS
    UNK_ERROR_INVALID_ARGUMENT = 5,    // ONE OR MORE FUNCTION ARGUMENTS ARE OUT OF VALID RANGE
} unk_error_code_t;

#endif // __UNKNOWN_ERROR__