#ifndef __UNKNOWN_ERROR__
#define __UNKNOWN_ERROR__

typedef enum
{
    UNK_ERROR_NONE = 0,
    UNK_ERROR_NH_RADIUS_TOO_BIG = 1,
    UNK_ERROR_FILE_DOES_NOT_EXIST = 2,
    UNK_ERROR_FILE_SIZE_WRONG = 3,
    UNK_ERROR_FAILED_ALLOC = 4,
    UNK_ERROR_CORTEX_UNALLOC = 5,
    UNK_ERROR_SIZE_WRONG = 6,
    UNK_ERROR_INVALID_ARGUMENT = 7
} unk_error_code_t;

#endif
