name: 'CI'
on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]
jobs:
  CI:
    name: 'CI'
    runs-on: ubuntu-latest
    steps:
    - name: 'CHECKOUT'
      uses: actions/checkout@v4
    - name: 'INSTALL STD'
      run: make std
    - name: 'INSTALL CUDA'
      run: make cuda
    - name: 'INSTALL HEADERS'
      run: make install-headers
    - name: 'INSTALL LIB'
      run: make install-lib
    - name: 'UNINSTALL'
      run: make uninstall