name: 'CI'
on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]
jobs:
  CI:
    name: 'CI'
    runs-on: ubuntu-latest
    steps:
    - name: 'CHECKOUT'
      uses: actions/checkout@v4
    - name: 'INSTALL'
      run: sudo apt-get update -y && sudo apt install make gcc g++ -y && make install
    - name: 'UNINSTALL'
      run: make uninstall