name: 'CI'
on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]
jobs:
  CI:
    name: 'CI'
    runs-on: ubuntu-latest
    steps:
    - name: 'CHECKOUT'
      uses: actions/checkout@v4
    - name: 'INSTALL'
      run: make install
    - name: 'BENCHMARK'
      run: cd test/std && make && ./bin/bench -c
    - name: 'UNINSTALL'
      run: make uninstall
