name: "CODE SECURITY"
on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]
  schedule:
    - cron: '29 21 * * 1'
jobs:
  CODE_SECURITY:
    name: 'CODE SECURITY'
    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
        - language: c-cpp
          build-mode: autobuild
    steps:
    - name: 'CHECKOUT'
      uses: actions/checkout@v4
    - name: 'INITIALIZE PRIMARY SCAN'
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
        build-mode: ${{ matrix.build-mode }}
    - name: 'RUN PRIMARY SCAN'
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"