name: 'TAG'
on:
  pull_request:
    types: [ merged ]
    branches: [ "trunk" ]
jobs:
  TAG:
    name: 'TAG'
    runs-on: ubuntu-latest
    steps:
      - name: 'CHECKOUT'
        uses: actions/checkout@v4
      - name: 'INFER TAG NAME'
        id: 'INFER_TAG_NAME'
        run: |
          DATE=$(date '+%Y.%m.%d')
          TAG_NAME="${DATE}.1000"
          while git tag -l "${TAG_NAME}" &> /dev/null; do
            TAG_NAME=$(echo "${TAG_NAME}" | awk -F '.' '{print $1"."$2"."$3"."$4+1}')
          done
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
      - name: 'RENAME PULL REQUEST TITLE'
        run: |
          TAG_NAME=$(echo "${{ steps.INFER_TAG_NAME.outputs.TAG_NAME }}")
          gh pr edit "$(gh pr view --json title --jq '.title = "TAG-'${TAG_NAME}'" | jq -r '.title')"
      - name: 'RENAME GITHUB_REF'
        run: |
          TAG_NAME=$(echo "${{ steps.INFER_TAG_NAME.outputs.TAG_NAME }}")
          git branch -m "${{ github.GITHUB_REF }}" "TAG-${TAG_NAME}"
          git fetch origin
          git branch -u origin/"TAG-${TAG_NAME}" "TAG-${TAG_NAME}"
          git remote set-head origin -a
      - name: 'UPDATE LAST COMMIT & CREATE TAG'
        run: |
          TAG_NAME=$(echo "${{ steps.INFER_TAG_NAME.outputs.TAG_NAME }}")
          git checkout "${{ github.GITHUB_BASE_REF }}"
          git commit --amend -m "TAG-${TAG_NAME}" -S
          git tag "${TAG_NAME}"
          git push --force origin HEAD:"${{ github.GITHUB_BASE_REF }}"
          git push origin "${TAG_NAME}"