name: 'TAG'
on:
  pull_request:
    types: [ closed ]
    branches: [ "trunk" ]
jobs:
  TAG:
    name: 'TAG'
    runs-on: ubuntu-latest
    steps:
      - name: 'CHECKOUT'
        uses: actions/checkout@v4
      - name: 'UPDATE LAST COMMIT & CREATE TAG'
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        run: |
          git checkout trunk
          git tag "$(git log -1 --pretty=format:"%s" trunk | grep -oP ".*?(?=\()" | sed 's/ //g' | tr '[:upper:]' '[:lower:]')"
          git push --force origin HEAD:trunk
          git push origin "$(git log -1 --pretty=format:"%s" trunk | grep -oP ".*?(?=\()" | sed 's/ //g' | tr '[:upper:]' '[:lower:]')"